homeassistant:
  name: Briggs Home Assistant
  packages: !include_dir_named packages

default_config:

pyscript:
  allow_all_imports: true
  apps: !include pyscript/apps.yaml

logger:
  default: warning
  logs:
    custom_components.pyscript: debug
    custom_components.pyscript.file:  debug

tts:
  - platform: google_translate

script: !include scripts.yaml
scene: !include scenes.yaml
