homeassistant:
  name: Briggs Home Assistant
  packages: !include_dir_named packages

default_config:

logger:
  default: warning

tts:
  - platform: google_translate

script: !include scripts.yaml
scene: !include scenes.yaml
