# =============================================================================
# PACKAGE: modes.yaml
# PURPOSE: Cross-domain "modes" coordinating Shelly shelves + Sonos
# ISSUE: #TBD
# DEPENDS ON:
#   - shelly_shelves.yaml scripts (shelf_set_mode_*, seahawks_touchdown, shelves_*)
#   - sonos.yaml scripts (sonos_group_with, sonos_announce, etc.)
# TESTED ON: Home Assistant Core 2025.8.3 (Container), Sonos S2 16.2
# NOTES:
#   - Mode scripts keep Sonos grouping optional per room preference.
# =============================================================================

homeassistant:
  customize:
    script.mode_tv:
      google_assistant: true
      google_assistant_name: "Mode TV"
      google_assistant_aliases:
        - "Set house to TV mode"
        - "TV lighting mode"
        - "Activate TV scene"
    script.mode_chill:
      google_assistant: true
      google_assistant_name: "Mode Chill"
      google_assistant_aliases:
        - "Set house to chill mode"
        - "Chill lighting mode"
        - "Activate relax scene"
    script.mode_party:
      google_assistant: true
      google_assistant_name: "Mode Party"
      google_assistant_aliases:
        - "Set house to party mode"
        - "Party lighting mode"
        - "Activate party scene"
    script.mode_game_day:
      google_assistant: true
      google_assistant_name: "Mode Game Day"
      google_assistant_aliases:
        - "Set house to game day"
        - "Game day lighting mode"
        - "Activate Seahawks mode"
    script.seahawks_touchdown_combo:
      google_assistant: true
      google_assistant_name: "Seahawks Touchdown"
      google_assistant_aliases:
        - "Touchdown Seahawks"
        - "Seahawks celebration"
        - "Run the Seahawks touchdown"

script:

  mode_tv:
    alias: "Mode - TV"
    mode: restart
    sequence:
      - service: script.shelf_set_mode_tv
      # Optionally also group Kitchen:
      # - service: script.sonos_group_with
      #   data:
      #     coordinator: media_player.family_room
      #     members: [media_player.kitchen]
      # - service: media_player.volume_set
      #   target: { entity_id: media_player.kitchen }
      #   data: { volume_level: 0.30 }

  mode_chill:
    alias: "Mode - Chill"
    mode: restart
    sequence:
      - service: script.shelf_set_mode_chill
      # (No clamping)

  mode_party:
    alias: "Mode - Party"
    mode: restart
    sequence:
      - service: script.shelf_set_mode_party
      # Optionally group all Sonos:
      # - service: script.tv_whole_house

  mode_game_day:
    alias: "Mode - Game Day"
    mode: restart
    sequence:
      - service: script.shelf_set_mode_game_day

  seahawks_touchdown_combo:
    alias: "Combo - Seahawks Touchdown"
    mode: single
    sequence:
      - service: script.seahawks_touchdown
      # Optionally:
      # - service: script.sonos_announce
      #   data:
      #     players: [media_player.family_room]
      #     message: "Touchdown Seahawks!"
      #     volume: 0.35

  doorbell_flash_combo:
    alias: "Combo - Doorbell Flash"
    mode: restart
    sequence:
      - service: script.shelves_doorbell_flash
      # Optionally:
      # - service: script.sonos_announce
      #   data:
      #     players: [media_player.family_room]
      #     message: "Someone is at the front door."
      #     volume: 0.25

