# =============================================================================
# PACKAGE: ring.yaml
# PURPOSE: Ring ding → flash Shelly shelves + play chime on Kitchen & Patio Sonos
#
# DEPENDS ON:
#   - Shelly shelves package providing script.shelves_doorbell_flash
#   - Sonos players: media_player.kitchen, media_player.patio
#   - File at /config/www/dingdong.mp3 → media-source://media_source/local/dingdong.mp3
#
# NOTES:
#   - All steps use `service:` (canonical). UI may say “Actions”, YAML uses `service`.
#   - Media Source URI avoids expiring auth tokens per ADR-0005.
# =============================================================================

script:
  sonos_doorbell_chime:
    alias: Sonos - Doorbell Chime (Kitchen + Patio)
    mode: single
    variables:
      players:
        - media_player.kitchen
        - media_player.patio
      chime_url: "media-source://media_source/local/dingdong.mp3"
      chime_vol: 0.40
      chime_len: "00:00:03"
    sequence:
      - service: sonos.snapshot
        target: { entity_id: "{{ players }}" }
        data: { with_group: true }
      - repeat:
          for_each: "{{ players }}"
          sequence:
            - service: media_player.volume_set
              target: { entity_id: "{{ repeat.item }}" }
              data: { volume_level: "{{ chime_vol }}" }
      - repeat:
          for_each: "{{ players }}"
          sequence:
            - service: media_player.play_media
              target: { entity_id: "{{ repeat.item }}" }
              data:
                media_content_id: "{{ chime_url }}"
                media_content_type: music
            - delay: "00:00:00.20"
      - delay: "{{ chime_len }}"
      - service: sonos.restore
        target: { entity_id: "{{ players }}" }
        data: { with_group: true }

automation:
  - alias: Ring → Ding-Dong + Shelves Flash
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: event.front_door_ding   # state changes to a new timestamp each press
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.get('event_type') == 'ding' }}"
    action:
      - service: script.shelves_doorbell_flash
      - delay: "00:00:00.15"     # tiny stagger so Shellys start before audio
      - service: script.sonos_doorbell_chime
      - delay: "00:00:04"        # absorb duplicates
