# =============================================================================
# PACKAGE: ring.yaml
# PURPOSE: Ring ding → flash Shelly shelves + play chime on Kitchen & Patio Sonos
#
# DEPENDS ON:
#   - Shelly shelves package providing script.shelves_doorbell_flash
#   - Sonos players: media_player.kitchen, media_player.patio
#   - File at /config/www/dingdong.mp3 (served via media-source://media_source/local/dingdong.mp3)
#
# NOTES:
#   - All steps use `service:` (canonical). UI may say “Actions”, YAML uses `service`.
#   - If you prefer a direct URL, swap chime_url to
#       http://<HA-IP>:8123/local/dingdong.mp3
#     and keep media_content_type: music.
# =============================================================================

script:
  sonos_doorbell_chime:
    alias: Sonos - Doorbell Chime (Kitchen + Patio)
    mode: single
    variables:
      players:
        - media_player.kitchen
        - media_player.patio
      chime_url: "media-source://media_source/local/dingdong.mp3"  # /config/www/dingdong.mp3
      chime_vol: 0.40
      chime_len: "00:00:03"
    sequence:
      - variables:
          plist_source: >-
            {% set candidate = players | default([], true) %}
            {% if candidate is mapping and 'entity_id' in candidate %}
              {% set candidate = candidate.entity_id %}
            {% endif %}
            {% if candidate is iterable and candidate is not string %}
              {% set items = candidate | list %}
            {% elif candidate is none %}
              {% set items = [] %}
            {% else %}
              {% set items = [candidate] %}
            {% endif %}
            {% set ns = namespace(result=[]) %}
            {% for item in items %}
              {% if item is mapping and 'entity_id' in item %}
                {% set value = item.entity_id %}
              {% else %}
                {% set value = item %}
              {% endif %}
              {% if value is not none %}
                {% set _ = ns.result.append(value | string) %}
              {% endif %}
            {% endfor %}
            {{ ns.result | to_json }}
      - variables:
          plist: "{{ plist_source | from_json }}"
      - condition: template
        value_template: "{{ plist | length > 0 }}"
      - service: sonos.snapshot
        target:
          entity_id: "{{ plist }}"
        data:

          with_group: true
      - repeat:
          for_each: "{{ plist }}"
          sequence:
            - service: media_player.volume_set
              target:
                entity_id: "{{ repeat.item }}"
              data:
                volume_level: "{{ chime_vol | float }}"

      - repeat:
          for_each: "{{ plist }}"
          sequence:
            - service: media_player.play_media
              target:
                entity_id: "{{ repeat.item }}"
              data:
                entity_id: "{{ repeat.item }}"
                media_content_id: "{{ chime_url }}"
                media_content_type: music
            - delay: "00:00:00.20"
      - delay: "{{ chime_len }}"
      - service: sonos.restore
        target:
          entity_id: "{{ plist }}"
        data:
          with_group: true

automation:
  - alias: Ring → Ding-Dong + Shelves Flash
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: event.front_door_ding   # state changes to a new timestamp each press
    condition:
      - condition: template
        value_template: >-
          {% set attrs = trigger.to_state.attributes %}
          {% set event_type = attrs.get('event_type') %}
          {% set data = attrs.get('event_data', {}) %}
          {% set kind = data.get('kind') %}
          {% set state = data.get('state') %}
          {{ event_type == 'ding'
             and (kind is none or kind in ['ding', 'doorbell', 'on_demand_ding', 'remote_ding'])
             and (state is none or state in ['ringing', 'starting']) }}
    action:
      - service: script.shelves_doorbell_flash
      - delay: "00:00:00.15"     # tiny stagger so Shellys start before audio
      - service: script.sonos_doorbell_chime
      - delay: "00:00:04"        # absorb duplicates
