# =============================================================================
# PACKAGE: ring.yaml
# PURPOSE: Ring ding → flash Shelly shelves + play chime on Kitchen & Patio Sonos
# ISSUE: #TBD
# DEPENDS ON:
#   - Shelly shelves package providing script.shelves_doorbell_flash
#   - Sonos players: media_player.kitchen, media_player.patio
#   - File at /config/www/dingdong.mp3 served via media-source://media_source/local/dingdong.mp3
# TESTED ON: Home Assistant Core 2025.8.3 (Container), Sonos S2 16.2
# NOTES:
#   - All steps use `service:` (canonical). UI may say “Actions”, YAML uses `service`.
#   - Media Source URI avoids expiring auth tokens per ADR-0005.
# =============================================================================

script:
  sonos_doorbell_chime:
    alias: Sonos - Doorbell Chime (Kitchen + Patio)
    mode: single
    variables:
      players: &doorbell_players
        - media_player.kitchen
        - media_player.patio
      chime_url: "media-source://media_source/local/dingdong.mp3"
      chime_vol: 0.40
      chime_len: "00:00:03"
    sequence:
      - service: script.sonos_snapshot
        data:
          players: *doorbell_players
      - repeat:
          for_each: *doorbell_players
          sequence:
            - service: media_player.volume_set
              data:
                entity_id: "{{ repeat.item }}"
                volume_level: "{{ chime_vol }}"
      - repeat:
          for_each: *doorbell_players
          sequence:
            - service: media_player.play_media
              data:
                entity_id: "{{ repeat.item }}"
                media_content_id: "{{ chime_url }}"
                media_content_type: music
            - delay: "00:00:00.20"
      - delay: "{{ chime_len }}"
      - service: script.sonos_restore_snapshot
        data:
          players: *doorbell_players

automation:
  - alias: Ring → Ding-Dong + Shelves Flash
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: event.front_door_ding   # state changes to a new timestamp each press
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.get('event_type') == 'ding' }}"
    action:
      - service: script.shelves_doorbell_flash
      - delay: "00:00:00.15"     # tiny stagger so Shellys start before audio
      - service: script.sonos_doorbell_chime
      - delay: "00:00:04"        # absorb duplicates
